### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by dashawk** [JKHeadley/rest-hapi#16]
I tried to use your demo repo and tried to seed my model using `./node_modules/.bin/rest-hapi-cli seed` or `rest-hapi-cli seed` for global, but it keeps on saying `No gulpfile found` even if I already have a gulpfile.js in the directory.

**Comment by JKHeadley** [comment]
Hmm, sounds like you're running the command from the wrong directory.  If you're following the [rest-hapi-demo](https://github.com/JKHeadley/rest-hapi-demo) then make sure you run the seed command from within the rest-hapi-demo directory.

As a side note, I noticed some of the rest-hapi-demo code was out of date, so I pushed an update.  Make sure you pull the updates to get the best functionality.

**Comment by dashawk** [comment]
Thank you for looking into this, but I still have the same error. I executed the command in the root directory of the demo app.

Here is the screenshot I recently took.
![image](https://cloud.githubusercontent.com/assets/1437205/25363930/438bc720-2991-11e7-83c9-6889d56362d1.png)

**Comment by dashawk** [comment]
I've been digging the cli command and created a PR #17 for this issue.

**Comment by JKHeadley** [comment]
Thanks for the fix!
